"""add avatar hash

Revision ID: 294e252d6219
Revises: c89e30c322cf
Create Date: 2017-08-23 12:35:12.372243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294e252d6219'
down_revision = 'c89e30c322cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
